# Statistical Calculator

https://www.evanmiller.org/ab-testing/

## Sample Size Calculator

https://stackoverflow.com/questions/15204070/is-there-a-python-scipy-function-to-determine-parameters-needed-to-obtain-a-ta

In [26]:
from scipy.stats import norm, zscore

def sample_power_probtest(p1, p2, power=0.8, sig=0.05):
    z = norm.isf([sig/2]) #two-sided t test
    zp = -1 * norm.isf([power]) 
    d = (p1-p2)
    s =2*((p1+p2) /2)*(1-((p1+p2) /2))
    n = s * ((zp + z)**2) / (d**2)
    return int(round(n[0]))

def sample_power_difftest(d, s, power=0.8, sig=0.05):
    z = norm.isf([sig/2])
    zp = -1 * norm.isf([power])
    n = s * ((zp + z)**2) / (d**2)
    return int(round(n[0]))

## Chi-Squared Test

https://stackoverflow.com/questions/26615019/python-proportion-test-similar-to-prop-test-in-r

In [ ]:
np.array([100])

In [10]:
survivors = np.array([[100,14], [100, 20]])

In [11]:
from scipy import stats
import numpy as np

# survivors = np.array([[1781,135], [1443, 47]])
result = stats.chi2_contingency(survivors)

In [13]:
result[1]

(0.58683378482972248,
 0.44364609286729395,
 1,
 array([[  97.43589744,   16.56410256],
        [ 102.56410256,   17.43589744]]))

In [14]:
from statsmodels.stats.proportion import proportions_chisquare

In [16]:
successes = np.array([14,20])
trials = np.array([100,100])

In [19]:
result = proportions_chisquare(successes,trials)

In [21]:
result[1]

0.25870176105718623

### Sample Proportion CI's

https://select-statistics.co.uk/calculators/confidence-interval-calculator-population-proportion/
    

In [1]:
from scipy.stats.mstats import zscore
samp_prop = 0.14

In [22]:
import numpy as np

from scipy.stats import norm
norm.ppf(.99)

2.3263478740408408

In [34]:
sample1_prop = 0.14
sample1_trials = 100

In [35]:
z_score = norm.ppf(1-(1-0.99)/2)

In [36]:
err1 = (float(z_score))* \
np.sqrt( (sample1_prop * ( 1-sample1_prop))/int(sample1_trials))

In [39]:
err1

0.089377936358083027

In [38]:
print(.14-err1,.14+err1)

0.0506220636419 0.229377936358


## Sequential Sampling

## 2 Sample T-Test

In [1]:
from scipy.stats import ttest_ind, ttest_ind_from_stats


NameError: name 'a' is not defined

In [2]:
a = [54,231,554,322,553,111]
b = [54,231,554,322,553,111]

In [3]:
t, p = ttest_ind(a, b, equal_var=False)

In [4]:
p

1.0

In [43]:
import numpy as np,pandas as pd
pd.Series(np.random.randn(5))

0   -0.015297
1    0.055816
2    1.109691
3   -0.534066
4    0.974829
dtype: float64

In [49]:
x = [64.2,28.4,85.3,83.1,13.4,56.8,44.2,90]

In [50]:
type(x)

list

In [53]:
import plotly.plotly as py
import plotly.graph_objs as go
from plotly import tools

import numpy as np
from scipy.stats import norm
from sklearn.neighbors import KernelDensity

In [73]:
X = np.concatenate((np.random.normal(0, 1, 0.3 * N),
                    np.random.normal(5, 1, 0.7 * N)))[:, np.newaxis]

X_plot = np.linspace(-5, 10, 1000)[:, np.newaxis]

/Users/Collier/miniconda3/envs/env1/lib/python3.5/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning:

using a non-integer number instead of an integer will result in an error in the future

/Users/Collier/miniconda3/envs/env1/lib/python3.5/site-packages/ipykernel/__main__.py:2: VisibleDeprecationWarning:

using a non-integer number instead of an integer will result in an error in the future



In [74]:
X

array([[-1.10061918],
       [ 1.14472371],
       [ 0.90159072],
       [ 0.50249434],
       [ 0.90085595],
       [-0.68372786],
       [ 4.87710977],
       [ 4.06423057],
       [ 4.73211192],
       [ 5.53035547],
       [ 4.30833925],
       [ 4.60324647],
       [ 4.3128273 ],
       [ 4.15479436],
       [ 4.32875387],
       [ 4.9873354 ],
       [ 3.88268965],
       [ 5.2344157 ],
       [ 6.65980218],
       [ 5.74204416]])

In [75]:
X_plot

array([[ -5.        ],
       [ -4.98498498],
       [ -4.96996997],
       [ -4.95495495],
       [ -4.93993994],
       [ -4.92492492],
       [ -4.90990991],
       [ -4.89489489],
       [ -4.87987988],
       [ -4.86486486],
       [ -4.84984985],
       [ -4.83483483],
       [ -4.81981982],
       [ -4.8048048 ],
       [ -4.78978979],
       [ -4.77477477],
       [ -4.75975976],
       [ -4.74474474],
       [ -4.72972973],
       [ -4.71471471],
       [ -4.6996997 ],
       [ -4.68468468],
       [ -4.66966967],
       [ -4.65465465],
       [ -4.63963964],
       [ -4.62462462],
       [ -4.60960961],
       [ -4.59459459],
       [ -4.57957958],
       [ -4.56456456],
       [ -4.54954955],
       [ -4.53453453],
       [ -4.51951952],
       [ -4.5045045 ],
       [ -4.48948949],
       [ -4.47447447],
       [ -4.45945946],
       [ -4.44444444],
       [ -4.42942943],
       [ -4.41441441],
       [ -4.3993994 ],
       [ -4.38438438],
       [ -4.36936937],
       [ -4

## Survival Times

## Count Data